version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  nodebb:
    user: "0"
    build: .
    restart: unless-stopped
    depends_on:
      translator:
        condition: service_started
    ports:
      - '4567:4567'
    volumes:
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-config:/opt/config
      - ./install/docker/setup.json:/usr/src/app/setup.json
    environment:
      - TRANSLATOR_SERVICE_URL=http://translator:8080

  mongo:
    image: mongo:7-jammy
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodebb
      MONGO_INITDB_ROOT_PASSWORD: nodebb
      MONGO_INITDB_DATABASE: nodebb
    volumes:
      - mongo-data:/data/db
      - ./install/docker/mongodb-user-init.js:/docker-entrypoint-initdb.d/user-init.js

  redis:
    image: redis:8.0.1-alpine
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes', '--loglevel', 'warning']
    volumes:
      - redis-data:/data
    profiles:
      - redis

  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - postgres

  translator:
    build:
      context: https://github.com/CMU-313/llm-experiment-microservice-blind-hikers.git#f25
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      - PORT=8080
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - '8080:8080'

volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/mongo/data

  redis-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/redis

  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/postgresql/data

  nodebb-build:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/build

  nodebb-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/public/uploads

  nodebb-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/config

  ollama_data:

